name: Lighthouse Audit
on: push

jobs:
  audit:
    env:
      sitemap: 'https://katydecorah.com/\nhttps://katydecorah.com/playlists/2019-summer/\nhttps://katydecorah.com/epicurean/cowboy-cookie-ice-cream/\nhttps://katydecorah.com/code/google-sheets-to-gmail-template/'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse and ensure performance budget
        uses: treosh/lighthouse-ci-action@v1
        with:
          onlyCategories: performance,accessibility,best-practices,seo
          urls: ${{env.sitemap}}
      - name: Create scores.md
        uses: ./ # Uses an action in the root directory
        with:
          FILEPATH: ${{ github.workspace }}/results/
      - name: Save results
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-results
          path: './results'
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: scores.md
          path: ./scores.md
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: Lighthouse Audit
          ISSUE_CONTENT_FILEPATH: ./scores.md
