name: Lighthouse Audit
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@master
        with:
          url: "https://katydecorah.com/"
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          CONTENT_FILEPATH: cat $GITHUB_WORKSPACE/report/https___katydecorah_com_.report.json
      # Use the output from the `hello` step
      - name: Get the output json
        run: echo "The json was ${{ steps.hello.outputs.json }}"
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: scores.md
          path: ./scores.md
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: Lighthouse Audit
          ISSUE_CONTENT_FILEPATH: ./scores.md
      
