name: Lighthouse Audit
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@master
        with:
          url: "https://katydecorah.com/"
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
      
